# Generated by Django 4.0.2 on 2022-02-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(default='default-ingredient.jpg', upload_to='ingredient-pics'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default-recipe.jpg', upload_to='recipe-pics'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(default='Delicious cooking ingredient'),
        ),
    ]
