# Generated by Django 4.0.2 on 2022-02-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0002_ingredient_image_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='A fantastic recipe!'),
        ),
    ]
