# Generated by Django 4.0.2 on 2022-02-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0004_recipe_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_id',
            new_name='id',
        ),
    ]
